name: "1155 deployments"
on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      precache: "pnpm run generate"
      package_folder: packages/1155-deployments

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      package_folder: packages/1155-deployments
      precache: "pnpm run generate"
      name: Deployments
    secrets: inherit
